const Map<String, Map<String, Object>> generatedAppStringsData = {
  "en": {
    "appTitle": "CreatorFlow Native UI",
    "appBrandName": "CreatorFlow",
    "languageLabel": "Language",
    "englishLabel": "English",
    "indonesianLabel": "Indonesia",
    "dashboard": "Dashboard",
    "content": "Content",
    "trend": "Trend",
    "assets": "Assets",
    "billing": "Billing",
    "profile": "Profile",
    "nativeShellAligned": "Native shell aligned with the current web dashboard.",
    "signedInAsTemplate": "Signed in as {{email}}",
    "previewMode": "Preview Mode",
    "signOut": "Sign out",
    "signInTitle": "Sign In",
    "signInSubtitleTemplate": "Enter your email and password to access {{appName}}. Native auth will call api-gateway directly.",
    "email": "Email",
    "emailHint": "name@creatorflow.app",
    "password": "Password",
    "passwordHint": "Enter your password",
    "fullName": "Full name",
    "connecting": "Connecting...",
    "enterWorkspace": "Enter Workspace",
    "needAccount": "Need an account? Create workspace",
    "forgotPasswordLink": "Forgot password?",
    "signInWithProviders": "Sign in with",
    "signUpWithProviders": "Create account with",
    "continueWithGoogle": "Continue with Google",
    "continueWithTwitter": "Continue with X / Twitter",
    "continueWithFacebook": "Continue with Facebook",
    "continueWithApple": "Continue with Apple",
    "nativeSsoHint": "SSO uses the system browser so the same provider flow works across mobile and desktop.",
    "authContract": "Native auth contract",
    "authClientInfoTemplate": "Client type: {{clientType}}. API base URL: {{apiBaseUrl}}.",
    "attentionQuote": "Attention is the new currency.",
    "signInSideBody": "This native shell reuses the current web visual direction while staying mobile and desktop friendly.",
    "createWorkspaceTitle": "Create Workspace",
    "createWorkspaceSubtitle": "Create a workspace and get native tokens from api-gateway.",
    "workspaceName": "Workspace name",
    "creating": "Creating...",
    "createAndContinue": "Create and continue",
    "forgotPasswordTitle": "Reset password",
    "forgotPasswordSubtitle": "Request a one-time code, then set a fresh password for your CreatorFlow account.",
    "otpCode": "OTP code",
    "otpCodeHint": "Enter the 6-digit code",
    "newPassword": "New password",
    "newPasswordHint": "Enter a new password",
    "requestResetCode": "Send reset code",
    "requestingResetCode": "Sending code...",
    "resetPassword": "Reset password",
    "resettingPassword": "Resetting password...",
    "requestAnotherCode": "Request another code",
    "backToSignIn": "Back to sign in",
    "resetCodeSent": "If the email exists, a reset code has been sent.",
    "passwordResetSuccess": "Password reset successful.",
    "forgotPasswordSideTitle": "Recovery without support tickets.",
    "forgotPasswordSideBody": "A short OTP email keeps password recovery direct and friendly on mobile, tablet, and desktop.",
    "contentPipeline": "Content Pipeline",
    "contentPipelineBody": "This screen will replace the dense web table with card-first content drafts and generator actions.",
    "assetLibrary": "Asset Library",
    "assetLibraryBody": "Desktop can use denser grids here, while mobile stays card and filter driven.",
    "watchlistOverview": "Watchlist Overview",
    "watchlistOverviewBody": "Trend digest and watchlist sections can map directly from api-gateway trend endpoints.",
    "billingOverview": "Billing Overview",
    "billingOverviewBody": "Payment methods, invoices, and transactions from the web billing page can stack cleanly here.",
    "profileSummaryBody": "Profile summary and editable account sections will map from the current web profile screen.",
    "publicRelationsRole": "Public Relations",
    "trendWatchlist": "Trend Watchlist",
    "workspaceDetails": "Workspace Details",
    "noItemsYet": "No items yet",
    "noItemsBody": "Once the API has data, it will show up here.",
    "noDetailsYet": "No details yet",
    "noDetailsBody": "Sign in and load workspace data first.",
    "fromLastCheckpointTemplate": "{{delta}} from last checkpoint",
    "unableToLoadDashboardTemplate": "Unable to load dashboard: {{error}}",
    "welcomeCreatorFlow": "Welcome to CreatorFlow",
    "signInToLoadWorkspace": "Sign in to load workspace and trend data.",
    "workspaceMetric": "Workspace",
    "watchlistItems": "Watchlist Items",
    "activeRecommendations": "active recommendations",
    "latestDigest": "Latest Digest",
    "notReadyYet": "not ready yet",
    "clientType": "Client Type",
    "member": "member",
    "connected": "connected",
    "active": "active",
    "profileIncomplete": "Profile incomplete",
    "nativeAuthReady": "Native auth ready",
    "noDigestYet": "No digest available yet. Create trend data from the API to enrich this screen.",
    "workspaceOverviewTemplate": "Workspace {{name}}",
    "overview": "overview",
    "profileLoading": "Loading profile details...",
    "profileSignInPrompt": "Sign in first to load your profile.",
    "accountCenter": "Account center",
    "editProfileTitle": "Edit profile",
    "about": "About",
    "aboutHint": "Add a short summary about you or your workspace.",
    "saveChanges": "Save changes",
    "savingChanges": "Saving...",
    "profileSaved": "Profile saved successfully.",
    "emailVerification": "Email verification",
    "verificationBody": "Request an OTP code, then enter it here to verify your email address.",
    "verificationDoneBody": "Your email is already verified.",
    "emailVerified": "Email verified",
    "emailNotVerified": "Email not verified",
    "verificationCode": "Verification code",
    "verificationCodeHint": "Enter the code from your email",
    "requestOtpCode": "Send OTP code",
    "requestingOtpCode": "Sending code...",
    "verifyEmail": "Verify email",
    "verifyingEmail": "Verifying...",
    "verificationCodeSent": "Verification code sent.",
    "verificationSucceeded": "Email verified successfully.",
    "securityStatus": "Security status",
    "statusLabel": "Status",
    "lastLogin": "Last login",
    "workspaceRole": "Workspace role",
    "connectedAccounts": "Connected accounts",
    "noConnectedAccounts": "No social account connected yet.",
    "connectedSinceTemplate": "Connected on {{date}}",
    "verifiedAtTemplate": "Verified on {{date}}",
    "googleLabel": "Google",
    "facebookLabel": "Facebook",
    "twitterLabel": "X / Twitter",
    "appleLabel": "Apple"
  },
  "id": {
    "appTitle": "CreatorFlow Native UI",
    "appBrandName": "CreatorFlow",
    "languageLabel": "Bahasa",
    "englishLabel": "Inggris",
    "indonesianLabel": "Indonesia",
    "dashboard": "Dashboard",
    "content": "Konten",
    "trend": "Tren",
    "assets": "Aset",
    "billing": "Tagihan",
    "profile": "Profil",
    "nativeShellAligned": "Native shell ini dibuat selaras dengan dashboard web saat ini.",
    "signedInAsTemplate": "Masuk sebagai {{email}}",
    "previewMode": "Mode Pratinjau",
    "signOut": "Keluar",
    "signInTitle": "Masuk",
    "signInSubtitleTemplate": "Masukkan email dan password untuk mengakses {{appName}}. Native auth akan memanggil api-gateway secara langsung.",
    "email": "Email",
    "emailHint": "name@creatorflow.app",
    "password": "Password",
    "passwordHint": "Masukkan password Anda",
    "fullName": "Nama lengkap",
    "connecting": "Sedang menghubungkan...",
    "enterWorkspace": "Masuk ke Workspace",
    "needAccount": "Belum punya akun? Buat workspace",
    "forgotPasswordLink": "Lupa password?",
    "signInWithProviders": "Masuk dengan",
    "signUpWithProviders": "Buat akun dengan",
    "continueWithGoogle": "Lanjut dengan Google",
    "continueWithTwitter": "Lanjut dengan X / Twitter",
    "continueWithFacebook": "Lanjut dengan Facebook",
    "continueWithApple": "Lanjut dengan Apple",
    "nativeSsoHint": "SSO memakai browser sistem agar flow provider yang sama tetap nyaman di mobile maupun desktop.",
    "authContract": "Kontrak auth native",
    "authClientInfoTemplate": "Tipe klien: {{clientType}}. Base URL API: {{apiBaseUrl}}.",
    "attentionQuote": "Perhatian adalah mata uang baru.",
    "signInSideBody": "Native shell ini memakai arah visual web saat ini sambil tetap nyaman dipakai di mobile maupun desktop.",
    "createWorkspaceTitle": "Buat Workspace",
    "createWorkspaceSubtitle": "Buat workspace dan dapatkan token native dari api-gateway.",
    "workspaceName": "Nama workspace",
    "creating": "Sedang membuat...",
    "createAndContinue": "Buat dan lanjutkan",
    "forgotPasswordTitle": "Reset password",
    "forgotPasswordSubtitle": "Minta kode OTP, lalu set password baru untuk akun CreatorFlow Anda.",
    "otpCode": "Kode OTP",
    "otpCodeHint": "Masukkan 6 digit kode",
    "newPassword": "Password baru",
    "newPasswordHint": "Masukkan password baru",
    "requestResetCode": "Kirim kode reset",
    "requestingResetCode": "Mengirim kode...",
    "resetPassword": "Reset password",
    "resettingPassword": "Sedang reset password...",
    "requestAnotherCode": "Minta kode baru",
    "backToSignIn": "Kembali ke halaman masuk",
    "resetCodeSent": "Jika email terdaftar, kode reset sudah dikirim.",
    "passwordResetSuccess": "Password berhasil direset.",
    "forgotPasswordSideTitle": "Recovery tanpa tiket support.",
    "forgotPasswordSideBody": "OTP email singkat menjaga recovery password tetap langsung dan nyaman di mobile, tablet, maupun desktop.",
    "contentPipeline": "Pipeline Konten",
    "contentPipelineBody": "Layar ini akan menggantikan tabel web yang padat dengan draft konten berbasis kartu dan aksi generator.",
    "assetLibrary": "Library Aset",
    "assetLibraryBody": "Versi desktop bisa memakai grid yang lebih rapat di sini, sementara mobile tetap berbasis kartu dan filter.",
    "watchlistOverview": "Ringkasan Watchlist",
    "watchlistOverviewBody": "Bagian digest tren dan watchlist bisa dipetakan langsung dari endpoint tren di api-gateway.",
    "billingOverview": "Ringkasan Tagihan",
    "billingOverviewBody": "Metode pembayaran, invoice, dan transaksi dari halaman billing web bisa ditumpuk rapi di sini.",
    "profileSummaryBody": "Ringkasan profil dan bagian akun yang bisa diedit akan dipetakan dari layar profil web saat ini.",
    "publicRelationsRole": "Hubungan Masyarakat",
    "trendWatchlist": "Watchlist Tren",
    "workspaceDetails": "Detail Workspace",
    "noItemsYet": "Belum ada item",
    "noItemsBody": "Saat API sudah punya data, datanya akan muncul di sini.",
    "noDetailsYet": "Belum ada detail",
    "noDetailsBody": "Masuk dulu dan muat data workspace.",
    "fromLastCheckpointTemplate": "{{delta}} dari checkpoint terakhir",
    "unableToLoadDashboardTemplate": "Tidak bisa memuat dashboard: {{error}}",
    "welcomeCreatorFlow": "Selamat datang di CreatorFlow",
    "signInToLoadWorkspace": "Masuk untuk memuat data workspace dan tren.",
    "workspaceMetric": "Workspace",
    "watchlistItems": "Item Watchlist",
    "activeRecommendations": "rekomendasi aktif",
    "latestDigest": "Digest Terbaru",
    "notReadyYet": "belum siap",
    "clientType": "Tipe Klien",
    "member": "anggota",
    "connected": "terhubung",
    "active": "aktif",
    "profileIncomplete": "Profil belum lengkap",
    "nativeAuthReady": "Auth native siap",
    "noDigestYet": "Belum ada digest. Buat data tren dari API untuk memperkaya layar ini.",
    "workspaceOverviewTemplate": "Workspace {{name}}",
    "overview": "ringkasan",
    "profileLoading": "Memuat detail profil...",
    "profileSignInPrompt": "Masuk dulu untuk memuat profil Anda.",
    "accountCenter": "Pusat akun",
    "editProfileTitle": "Edit profil",
    "about": "Tentang",
    "aboutHint": "Tambahkan ringkasan singkat tentang Anda atau workspace Anda.",
    "saveChanges": "Simpan perubahan",
    "savingChanges": "Menyimpan...",
    "profileSaved": "Profil berhasil disimpan.",
    "emailVerification": "Verifikasi email",
    "verificationBody": "Minta kode OTP, lalu masukkan di sini untuk memverifikasi alamat email Anda.",
    "verificationDoneBody": "Email Anda sudah terverifikasi.",
    "emailVerified": "Email terverifikasi",
    "emailNotVerified": "Email belum terverifikasi",
    "verificationCode": "Kode verifikasi",
    "verificationCodeHint": "Masukkan kode dari email",
    "requestOtpCode": "Kirim kode OTP",
    "requestingOtpCode": "Mengirim kode...",
    "verifyEmail": "Verifikasi email",
    "verifyingEmail": "Memverifikasi...",
    "verificationCodeSent": "Kode verifikasi dikirim.",
    "verificationSucceeded": "Email berhasil diverifikasi.",
    "securityStatus": "Status keamanan",
    "statusLabel": "Status",
    "lastLogin": "Login terakhir",
    "workspaceRole": "Peran workspace",
    "connectedAccounts": "Akun terhubung",
    "noConnectedAccounts": "Belum ada akun sosial yang terhubung.",
    "connectedSinceTemplate": "Terhubung pada {{date}}",
    "verifiedAtTemplate": "Terverifikasi pada {{date}}",
    "googleLabel": "Google",
    "facebookLabel": "Facebook",
    "twitterLabel": "X / Twitter",
    "appleLabel": "Apple"
  }
};
